---
- name: All TEAM1 VPC AND TEAM2 ASG Playbooks
  hosts: localhost
  tasks: 
  
  
  # TEAM 1  
  
- name: Create Vpc
  include: vpc.yaml

- name: Create Public Subnets
  include: public_subnet.yaml

- name: Create IGW
  include: internet_gateway.yaml

- name: Create Private Subnets
  include: private_subnet.yaml

- name: Create  Nat Gateway
  include: nat_gateway.yaml

- name: Create RT
  include: route_table_private.yaml

- name: Create RT
  include: route_table_public.yaml  
  
  # TEAM 2
  
- name: Create Security Group
  include: security_group.yaml

- name: Create Launch Config
  include: ec2_launch_configuration.yaml
  
- name: Create Target Group
  include: target_group.yaml

- name: Create Application Load Balancer
  include: application_load_balancer.yaml

- name: Create Auto Scaling Group
  include: auto_scaling_group.yaml
