---
- name: asg
  hosts: localhost
  ignore_errors: true
  tasks:
  - name: create launch config
    ec2_lc:
      name: launch_asg
      image_id: "{{image_d}}"
      key_name: "{{key_name}}"
      security_groups: "{{security_groups}}"
      instance_type: "{{instance_type}}"
      region: "{{region}}" 
      volumes:
      - device_name: "{{device_name}}"
        volume_size: "{{volume_sice}}"
        volume_type: "{{volume_type}}"
        iops: "{{iops}}"
        delete_on_termination: true
        encrypted: no
    register: lc
  
  - elb_target_group:
      name: mytargetgroup
      region: "{{region}}"
      protocol: http
      port: 80
      vpc_id: "{{vpc_id}}"
      state: present

  - elb_application_lb:
      name: myelb
      security_groups: "{{security_groups}}"
      region: "{{region}}"
      subnets:
        - "{{subnets}}"
        - "{{subnets}}"
        - "{{subnets}}"
      listeners:
        - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
          Port: 80
          DefaultActions:
            - Type: forward # Required.
              TargetGroupName: mytargetgroup
      state: present

  - ec2_asg:
      name: myasg
      launch_config_name: launch_asg
      health_check_period: "{{health_check_period}}"
      health_check_type: ELB
      replace_all_instances: yes
      min_size: "{{min_size}}"
      max_size: "{{max_size}}"
      desired_capacity: "{{desired_capacity}}"
      region: "{{region}}"
      state: present
  # - ec2_asg:
  #     name: myasg
  #     load_balancers: myelb
  #     launch_config_name: launch_asg
  #     availability_zones: [ 'eu-west-2a', 'eu-west-2b', 'eu-west-2c' ]
  #     min_size: 3
  #     max_size: 48
  #     desired_capacity: 3
  #     region: eu-west-2
  #     vpc_zone_identifier: [ 'subnet-0b4b71fdd6338c402', 'subnet-08a47152982b03821', 'subnet-00bcbb7fdfec17773' ]
  # - ec2_asg:
  #   name: myasg
  #   launch_config_name: my_new_lc
  #   health_check_period: 60
  #   health_check_type: ELB
  #   replace_instances:
  #   - i-b345231
  #   - i-24c2931
  #   min_size: 5
  #   max_size: 5
  #   desired_capacity: 5
  #   region: eu-west-2
