---
- name: asg
  hosts: localhost
  ignore_errors: true
  tasks:
  - name: create launch config
    ec2_lc:
      name: launch_asg
      image_id: ami-01d5e2046079dd35c
      key_name: ansible
      security_groups: launch-wizard-1
      instance_type: t2.micro
      region: eu-west-2 
      volumes:
      - device_name: /dev/xvda
        volume_size: 100
        volume_type: io1
        iops: 3000
        delete_on_termination: true
        encrypted: no
    register: lc
  
  - elb_target_group:
      name: mytargetgroup
      region: eu-west-2
      protocol: http
      port: 80
      vpc_id: vpc-0fc840bb81dca6ea8
      state: present

  - elb_application_lb:
      name: myelb
      security_groups: launch-wizard-1
      region: eu-west-2
      subnets:
        - subnet-0b4b71fdd6338c402
        - subnet-08a47152982b03821
        - subnet-00bcbb7fdfec17773
      listeners:
        - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
          Port: 80
          DefaultActions:
            - Type: forward # Required.
              TargetGroupName: mytargetgroup
      state: present

  # - name: tuba goes to sleep >>> after 5 hrs
  #   wait_for:
  #     timeout: 60
  - ec2_asg:
      name: myasg
      launch_config_name: launch_asg
      health_check_period: 60
      health_check_type: ELB
      replace_all_instances: yes
      min_size: 3
      max_size: 48
      desired_capacity: 3
      region: eu-west-2
      state: present
  # - ec2_asg:
  #     name: myasg
  #     load_balancers: myelb
  #     launch_config_name: launch_asg
  #     availability_zones: [ 'eu-west-2a', 'eu-west-2b', 'eu-west-2c' ]
  #     min_size: 3
  #     max_size: 48
  #     desired_capacity: 3
  #     region: eu-west-2
  #     vpc_zone_identifier: [ 'subnet-0b4b71fdd6338c402', 'subnet-08a47152982b03821', 'subnet-00bcbb7fdfec17773' ]
  # - ec2_asg:
  #   name: myasg
  #   launch_config_name: my_new_lc
  #   health_check_period: 60
  #   health_check_type: ELB
  #   replace_instances:
  #   - i-b345231
  #   - i-24c2931
  #   min_size: 5
  #   max_size: 5
  #   desired_capacity: 5
  #   region: eu-west-2
