---
- name: asg
  hosts: localhost
  ignore_errors: true
  tasks:
  - name: create launch config
    ec2_lc:
      name: launch_asg
      image_id: ami-0e8444967cca91ba6
      key_name: ansible
      assign_public_ip: yes
      security_groups: task
      instance_type: t2.micro
      region: us-west-2 
      volumes:
      - device_name: /dev/xvda
        volume_size: 100
        volume_type: io1
        iops: 3000
        delete_on_termination: true
        encrypted: no
    register: lc
  
  - elb_target_group:
      name: mytargetgroup
      region: us-west-2
      protocol: http
      port: 80
      vpc_id: vpc-06f28e2306844c115
      state: present

  - elb_application_lb:
      name: myelb
      security_groups: task
      region: us-west-2
      subnets:
        - subnet-068a4d74a47ea64fd
        - subnet-08c62c26854ad7054
        - subnet-044ea1def0c613d6e
      listeners:
        - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
          Port: 80
          DefaultActions:
            - Type: forward # Required.
              TargetGroupName: mytargetgroup
      state: present

  - ec2_asg:
      name: myasg
      launch_config_name: launch_asg
      vpc_zone_identifier: [ 'subnet-068a4d74a47ea64fd', 'subnet-08c62c26854ad7054', 'subnet-044ea1def0c613d6e'  ]
      health_check_period: 60
      health_check_type: ELB
      replace_all_instances: yes
      min_size: 3
      max_size: 48
      desired_capacity: 3
      region: us-west-2
      state: present