---
- name: Create Security Group
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars_file.yaml
  tasks: 
    - ec2_group:
        name: "{{ name }}"
        description: sg with rule descriptions
        vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
