---
- name: Create Target Group
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars_file.yaml
  tasks:

  - elb_target_group:
      name: team2targetgroup
      region: "{{region}}"
      protocol: http
      port: 80
      vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
      state: present
