---
- name: asg
  hosts: localhost 
  become: true
  become_method: sudo
  ignore_errors: true
  tasks:
  - name: create launch config
  ec2_lc:
    name: launch_asg
    image_id: ami-01a6e31ac994bbc09
    key_name: ansible
    security_groups: default
    instance_type: t2.micro
    volumes:
    - device_name: /dev/xvda
      volume_size: 100
      volume_type: io1
      iops: 3000
      delete_on_termination: true
      encrypted: no

  - local_action:
      module: ec2_elb_lb
      name: task_elb
      state: present
      region: eu-west-2
      zones:
        - eu-west-2a 
        - eu-west-2b
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
      
  - ec2_asg:
      name: myasg
      load_balancers: task_elb
      launch_config_name: launch_asg
      availability_zones: [ 'eu-west-2a', 'eu-west-2b', 'eu-west-2a' ]
      health_check_period: 60
      health_check_type: ELB
      replace_all_instances: yes
      min_size: 5
      max_size: 5
      desired_capacity: 5
      region: eu-west-2
      vpc_zone_identifier: [ 'subnet-0b4b71fdd6338c402', 'subnet-08a47152982b03821' ]