---
- name: Creates VPC
  hosts: localhost
  vars_files: 
  - region.yaml
  tasks:
  - name: Creates VPC
    ec2_vpc_net:
      name: Team1-project
      cidr_block: "{{vpc_cidr}}"
      region: "{{region}}"
      state: present
      tags:
          Class: Ansible
          Task: VPC
